/* eslint arrow-body-style: ["error", "as-needed", { "requireReturnForObjectLiteral": true }] */

export const logoURL = 'https://ericluciano.com/cripto-logos/';

export const moedas = {
  singular: {
    nome: 'singular',
    sigla: 'sngls_brl',
    width: 32,
    height: 32,
    logo: `${logoURL}/singular.png`,
  },
  tron: {
    nome: 'tron',
    sigla: 'trx_brl',
    width: 32,
    height: 32,
    logo: `${logoURL}/tron.png`,
  },
  ripple: {
    nome: 'ripple',
    sigla: 'xrp_brl',
    width: 32,
    height: 32,
    logo: `${logoURL}/ripple.png`,
  },
  bitcoin: {
    nome: 'bitcoin',
    sigla: 'btc_brl',
    width: 32,
    height: 32,
    logo: `${logoURL}/bitcoin.png`,
  },
  ethereum: {
    nome: 'ethereum',
    sigla: 'eth_brl',
    width: 32,
    height: 32,
    logo: `${logoURL}/ethereum.png`,
  },
  eos: {
    nome: 'eos',
    sigla: 'eos_brl',
    width: 32,
    height: 32,
    logo: `${logoURL}/eos.png`,
  },
  dash: {
    nome: 'dash',
    sigla: 'dash_brl',
    width: 32,
    height: 32,
    logo: `${logoURL}/dash.png`,
  },
  decred: {
    nome: 'decred',
    sigla: 'dcr_brl',
    width: 32,
    height: 32,
    logo: `${logoURL}/decred.png`,
  },
  litecoin: {
    nome: 'LiteCoin',
    sigla: 'ltc_brl',
    width: 32,
    height: 32,
    logo: `${logoURL}/litecoin.png`,
  },
  bitcoincash: {
    nome: 'Bitcoin Cash',
    sigla: 'bch_brl',
    width: 32,
    height: 32,
    logo: `${logoURL}/bitcoin-cash.png`,
  },
  bitcoingold: {
    nome: 'Bitcoin Gold',
    sigla: 'btg_brl',
    width: 32,
    height: 32,
    logo: `${logoURL}/bitcoin-gold.png`,
  },
  golem: {
    nome: 'Golem',
    sigla: 'gnt_brl',
    width: 32,
    height: 32,
    logo: `${logoURL}/golem.png`,
  },
  martexcoin: {
    nome: 'Martex Coin',
    sigla: 'mxt_brl',
    width: 32,
    height: 32,
    logo: `${logoURL}/martexcoin.png`,
  },
  binance: {
    nome: 'Binance',
    sigla: 'bnb_brl',
    width: 32,
    height: 32,
    logo: `${logoURL}/binance-coin.png`,
  },
  zcash: {
    nome: 'Z Cash',
    sigla: 'zec_brl',
    width: 32,
    height: 32,
    logo: `${logoURL}/zcash.png`,
  },
  omisego: {
    nome: 'OmiseGo',
    sigla: 'omg_brl',
    width: 32,
    height: 32,
    logo: `${logoURL}/omisego.png`,
  },
  monero: {
    nome: 'Monero',
    sigla: 'xmr_brl',
    width: 32,
    height: 32,
    logo: `${logoURL}/monero.png`,
  },
  crown: {
    nome: 'Crown',
    sigla: 'crw_brl',
    width: 32,
    height: 32,
    logo: `${logoURL}/crown.png`,
  },
  onix: {
    nome: 'Onix',
    sigla: 'onix_brl',
    width: 32,
    height: 32,
    logo: `${logoURL}/onix.png`,
  },
  litecoincash: {
    nome: 'LiteCoin Cash',
    sigla: 'lcc_brl',
    width: 32,
    height: 32,
    logo: `${logoURL}/litecoin-cash.png`,
  },
  tetherusdt: {
    nome: 'Tether USDT',
    sigla: 'usdt_brl',
    width: 32,
    height: 32,
    logo: `${logoURL}/tether.png`,
  },
  ethereumclassic: {
    nome: 'Ethereum Classic',
    sigla: 'etc_brl',
    width: 32,
    height: 32,
    logo: `${logoURL}/ethereum-classic.png`,
  },
};

export const symbolsCoin = {
  binance: 'BINANCE:BNBUSD',
  bitcoin: 'BITFINEX:BTCUSD',
  bitcoincash: 'BINANCE:BCCUSD',
  bitcoingold: 'BINANCE:BTGUSD',
  crown: 'BITTREX:CRWUSD',
  dash: 'BINANCE:DASHUSD',
  decred: 'POLONIEX:DCRUSD',
  eos: 'BINANCE:EOSUSD',
  ethereum: 'BINANCE:ETHUSD',
  ethereumclassic: 'BINANCE:ETCUSD',
  golem: 'POLONIEX:GNTUSD',
  litecoin: 'BINANCE:LTCUSD',
  litecoincash: 'CBOE:VXGOG',
  martexcoin: 'CBOE:VXGOG',
  monero: 'BINANCE:XMRUSD',
  omisego: 'BINANCE:OMGUSD',
  onix: 'CBOE:VXGOG',
  ripple: 'BINANCE:XRPUSD',
  singular: 'BINANCE:SNGLSUSD',
  tetherusdt: 'POLONIEX:USDTUSD',
  tron: 'BINANCE:TRXUSD',
  zcash: 'BITTREX:ZECUSD',
};
